apiVersion: skaffold/v3
kind: Config
metadata:
  name: imperio-linode-services
build:
  platforms: [ "linux/arm64" ]
  artifacts:
    - image: finda/imperio-linode-services
      docker:
        dockerfile: Dockerfile
#      sync:
#        infer:
#          - 'app/*'
#          - 'work/*'
#          - 'public/*'
#          - 'bin/*'
#          - 'package.json'
#          - 'app.ts'
manifests:
  rawYaml:
    - imperio-linode-services.yaml
